BEGIN_EVENT_TABLE(litFrame,wxFrame)
	EVT_CLOSE(litFrame::Exit)
    EVT_BUTTON(litGeneratedFrame::ID_AddIssue, litFrame::AddIssue)
    EVT_BUTTON(litGeneratedFrame::ID_DependencyButton, litFrame::DependencyPopup)
    EVT_LIST_ITEM_FOCUSED(litGeneratedFrame::ID_ListCtrl, litFrame::ItemFocused)
    EVT_TEXT(litGeneratedFrame::ID_NameTextCtrl, litFrame::NameChanged)
    EVT_TEXT(litGeneratedFrame::ID_ResourceTextCtrl, litFrame::ResourceChanged)
    EVT_TEXT(litGeneratedFrame::ID_ProjectsTextCtrl, litFrame::ProjectsChanged)
    EVT_TEXT(litGeneratedFrame::ID_DescriptionTextCtrl, litFrame::DescriptionChanged)
    EVT_RADIOBOX(litGeneratedFrame::ID_StatusBox, litFrame::StateChanged)
    EVT_CALENDAR_SEL_CHANGED(litGeneratedFrame::ID_StartCalendarCtrl, litFrame::StartChanged)
    EVT_CALENDAR_SEL_CHANGED(litGeneratedFrame::ID_EndCalendarCtrl, litFrame::EndChanged)
    EVT_MENU(litFrame::ID_New, litFrame::New)
    EVT_MENU(litFrame::ID_Save, litFrame::Save)
    EVT_MENU(litFrame::ID_SaveAs, litFrame::SaveAs)
    EVT_MENU(litFrame::ID_Open, litFrame::Open)
    EVT_MENU(litFrame::ID_About, litFrame::About)
    EVT_MENU(litFrame::ID_SaveGantt, litFrame::SaveGantt)
    EVT_MENU(litFrame::ID_SaveTrend, litFrame::SaveTrend)
    EVT_MENU_RANGE(litFrame::ID_Depend, litFrame::ID_DependEnd, litFrame::SelectDependency)
    EVT_MENU_RANGE(litFrame::ID_AddResource, litFrame::ID_AddResourceEnd, litFrame::AddResource)
    EVT_MENU_RANGE(litFrame::ID_AddProject, litFrame::ID_AddProjectEnd, litFrame::AddProject)
    EVT_MENU_RANGE(litFrame::ID_AddResourceFilter, litFrame::ID_AddResourceFilterEnd, litFrame::AddResourceFilter)
    EVT_MENU_RANGE(litFrame::ID_AddProjectFilter, litFrame::ID_AddProjectFilterEnd, litFrame::AddProjectFilter)
    EVT_CHECKBOX(litFrame::ID_AllCheckBox, litFrame::AllFilter)
    EVT_CHECKBOX(litFrame::ID_PlannedCheckBox, litFrame::FilterChanged)
    EVT_CHECKBOX(litFrame::ID_DelayedCheckBox, litFrame::FilterChanged)
    EVT_CHECKBOX(litFrame::ID_StartedCheckBox, litFrame::FilterChanged)
    EVT_CHECKBOX(litFrame::ID_FinishedCheckBox, litFrame::FilterChanged)
    EVT_CHECKBOX(litFrame::ID_CanceledCheckBox, litFrame::FilterChanged)
    EVT_CHECKBOX(litFrame::ID_MilestoneCheckBox, litFrame::MilestoneChanged)
    EVT_TEXT(litFrame::ID_ResourceFilterTextCtrl, litFrame::FilterChanged)
    EVT_TEXT(litFrame::ID_ProjectFilterTextCtrl, litFrame::FilterChanged)
    EVT_LIST_COL_CLICK(litFrame::ID_ListCtrl, litFrame::SortColumn)
    EVT_BUTTON(litFrame::ID_Resources, litFrame::ResourceMenu)
    EVT_BUTTON(litFrame::ID_Projects, litFrame::ProjectMenu)
    EVT_BUTTON(litFrame::ID_ResourcesFilter, litFrame::ResourceFilterMenu)
    EVT_BUTTON(litFrame::ID_ProjectsFilter, litFrame::ProjectFilterMenu)
    EVT_MENU(litFrame::ID_ClearResource, litFrame::ClearCtrl)
    EVT_MENU(litFrame::ID_ClearProject, litFrame::ClearCtrl)
    EVT_MENU(litFrame::ID_ClearResourceFilter, litFrame::ClearCtrl)
    EVT_MENU(litFrame::ID_ClearProjectFilter, litFrame::ClearCtrl)
END_EVENT_TABLE()
