// -*- C++ -*- generated by wxGlade 0.6.3 on Tue Jan  6 12:15:21 2009

#include "litGeneratedFrame.h"

// begin wxGlade: ::extracode

// end wxGlade


litGeneratedFrame::litGeneratedFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: litGeneratedFrame::litGeneratedFrame
    splitWindow = new wxSplitterWindow(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_BORDER);
    editPanel = new wxPanel(splitWindow, wxID_ANY);
    switchPanel = new wxPanel(editPanel, wxID_ANY);
    milestonePanel = new wxPanel(splitWindow, wxID_ANY);
    mainNotebook = new wxNotebook(milestonePanel, ID_Notebook, wxDefaultPosition, wxDefaultSize, 0);
    mainNotebook_pane_3 = new wxPanel(mainNotebook, wxID_ANY);
    mainNotebook_pane_2 = new wxPanel(mainNotebook, wxID_ANY);
    sizer_6_staticbox = new wxStaticBox(milestonePanel, -1, wxT("Filter"));
    sizer_8_staticbox = new wxStaticBox(switchPanel, -1, wxEmptyString);
    sizer_1_staticbox = new wxStaticBox(switchPanel, -1, wxT("Scheduled:"));
    mainNotebook_1 = new wxPanel(mainNotebook, wxID_ANY);
    mainFrame_menubar = new wxMenuBar();
    wxMenu* wxglade_tmp_menu_1 = new wxMenu();
    mainFrame_menubar->Append(wxglade_tmp_menu_1, wxT("File"));
    wxMenu* wxglade_tmp_menu_2 = new wxMenu();
    mainFrame_menubar->Append(wxglade_tmp_menu_2, wxT("Help"));
    SetMenuBar(mainFrame_menubar);
    milestoneListCtrl = new litIssueList(mainNotebook_1, ID_ListCtrl, wxDefaultPosition, wxDefaultSize, wxLC_REPORT|wxLC_VIRTUAL|wxLC_SINGLE_SEL|wxSUNKEN_BORDER);
    issueGantt = new litIssueGantt(mainNotebook_pane_2, ID_IssueGantt, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    issueTrend = new litTrend(mainNotebook_pane_3, ID_IssueTrend, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    plannedCheckBox = new wxCheckBox(milestonePanel, ID_PlannedCheckBox, wxT("planned"));
    finishedCheckBox = new wxCheckBox(milestonePanel, ID_FinishedCheckBox, wxT("finished"));
    delayedCheckBox = new wxCheckBox(milestonePanel, ID_DelayedCheckBox, wxT("delayed"));
    canceledCheckBox = new wxCheckBox(milestonePanel, ID_CanceledCheckBox, wxT("canceled"));
    startedCheckBox = new wxCheckBox(milestonePanel, ID_StartedCheckBox, wxT("started"));
    allCheckBox = new wxCheckBox(milestonePanel, ID_AllCheckBox, wxT("all"));
    button_3 = new wxButton(milestonePanel, ID_ResourcesFilter, wxT("Resource filter:"));
    ResourceFilterTextCtrl = new wxTextCtrl(milestonePanel, ID_ResourceFilterTextCtrl, wxEmptyString);
    button_4 = new wxButton(milestonePanel, ID_ProjectsFilter, wxT("Project filter:"));
    ProjectFilterTextCtrl = new wxTextCtrl(milestonePanel, ID_ProjectFilterTextCtrl, wxEmptyString);
    AddIssueButton = new wxButton(milestonePanel, ID_AddIssue, wxT("Add issue"));
    label_1 = new wxStaticText(switchPanel, wxID_ANY, wxT("Issue name:"));
    nameTextCtrl = new wxTextCtrl(switchPanel, ID_NameTextCtrl, wxEmptyString);
    button_1 = new wxButton(switchPanel, ID_Projects, wxT("Projects:"));
    projectsTextCtrl = new wxTextCtrl(switchPanel, ID_ProjectsTextCtrl, wxEmptyString);
    button_2 = new wxButton(switchPanel, ID_Resources, wxT("Resources:"));
    resourceTextCtrl = new wxTextCtrl(switchPanel, ID_ResourceTextCtrl, wxEmptyString);
    label_3 = new wxStaticText(switchPanel, wxID_ANY, wxT("Description:"));
    descriptionTextCtrl = new wxTextCtrl(switchPanel, ID_DescriptionTextCtrl, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    milestoneCheckBox = new wxCheckBox(switchPanel, ID_MilestoneCheckBox, wxT("This is a Milestone"));
    dependencyButton = new wxButton(switchPanel, ID_DependencyButton, wxT("This issue is necessary for ..."));
    label_4 = new wxStaticText(switchPanel, wxID_ANY, wxT("Start:"));
    label_5 = new wxStaticText(switchPanel, wxID_ANY, wxT("End:"));
    startCalendarCtrl = new wxCalendarCtrl(switchPanel, ID_StartCalendarCtrl, wxDefaultDateTime, wxDefaultPosition, wxDefaultSize, wxCAL_MONDAY_FIRST|wxCAL_SHOW_HOLIDAYS|wxCAL_SHOW_SURROUNDING_WEEKS|wxCAL_SEQUENTIAL_MONTH_SELECTION);
    endCalendarCtrl = new wxCalendarCtrl(switchPanel, ID_EndCalendarCtrl, wxDefaultDateTime, wxDefaultPosition, wxDefaultSize, wxCAL_MONDAY_FIRST|wxCAL_SHOW_HOLIDAYS|wxCAL_SHOW_SURROUNDING_WEEKS|wxCAL_SEQUENTIAL_MONTH_SELECTION);
    const wxString statusBox_choices[] = {
        wxT("planned"),
        wxT("started"),
        wxT("delayed"),
        wxT("finished"),
        wxT("canceled")
    };
    statusBox = new wxRadioBox(switchPanel, ID_StatusBox, wxT("Status:"), wxDefaultPosition, wxDefaultSize, 5, statusBox_choices, 0, wxRA_SPECIFY_COLS);

    set_properties();
    do_layout();
    // end wxGlade
}


void litGeneratedFrame::set_properties()
{
    // begin wxGlade: litGeneratedFrame::set_properties
    SetTitle(wxT("lit - lightweigt issue tracker"));
    SetSize(wxSize(999, 649));
    milestoneListCtrl->SetMinSize(wxSize(100, 80));
    issueGantt->SetScrollRate(10, 10);
    issueTrend->SetScrollRate(10, 10);
    plannedCheckBox->SetValue(1);
    delayedCheckBox->SetValue(1);
    startedCheckBox->SetValue(1);
    statusBox->SetSelection(0);
    // end wxGlade
}


void litGeneratedFrame::do_layout()
{
    // begin wxGlade: litGeneratedFrame::do_layout
    wxBoxSizer* topSizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* editSizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_7 = new wxBoxSizer(wxVERTICAL);
    wxStaticBoxSizer* sizer_1 = new wxStaticBoxSizer(sizer_1_staticbox, wxHORIZONTAL);
    wxFlexGridSizer* grid_sizer_2 = new wxFlexGridSizer(2, 2, 0, 10);
    wxBoxSizer* sizer_11 = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* sizer_8 = new wxStaticBoxSizer(sizer_8_staticbox, wxHORIZONTAL);
    wxFlexGridSizer* grid_sizer_1 = new wxFlexGridSizer(5, 2, 5, 5);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxVERTICAL);
    wxStaticBoxSizer* sizer_6 = new wxStaticBoxSizer(sizer_6_staticbox, wxHORIZONTAL);
    wxBoxSizer* sizer_10 = new wxBoxSizer(wxVERTICAL);
    wxFlexGridSizer* grid_sizer_4 = new wxFlexGridSizer(2, 2, 0, 0);
    wxBoxSizer* sizer_12 = new wxBoxSizer(wxVERTICAL);
    wxGridSizer* grid_sizer_3 = new wxGridSizer(3, 2, 0, 0);
    wxBoxSizer* sizer_9 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_5 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxHORIZONTAL);
    sizer_4->Add(milestoneListCtrl, 1, wxEXPAND, 0);
    mainNotebook_1->SetSizer(sizer_4);
    sizer_5->Add(issueGantt, 1, wxEXPAND, 0);
    mainNotebook_pane_2->SetSizer(sizer_5);
    sizer_9->Add(issueTrend, 1, wxEXPAND, 0);
    mainNotebook_pane_3->SetSizer(sizer_9);
    mainNotebook->AddPage(mainNotebook_1, wxT("Issues"));
    mainNotebook->AddPage(mainNotebook_pane_2, wxT("Gantt"));
    mainNotebook->AddPage(mainNotebook_pane_3, wxT("Trend"));
    sizer_3->Add(mainNotebook, 1, wxEXPAND, 0);
    grid_sizer_3->Add(plannedCheckBox, 0, wxRIGHT, 5);
    grid_sizer_3->Add(finishedCheckBox, 0, wxRIGHT, 5);
    grid_sizer_3->Add(delayedCheckBox, 0, wxRIGHT, 5);
    grid_sizer_3->Add(canceledCheckBox, 0, wxRIGHT, 5);
    grid_sizer_3->Add(startedCheckBox, 0, wxRIGHT, 5);
    grid_sizer_3->Add(allCheckBox, 0, 0, 0);
    sizer_6->Add(grid_sizer_3, 0, wxEXPAND, 0);
    sizer_6->Add(sizer_12, 0, wxEXPAND, 0);
    grid_sizer_4->Add(button_3, 0, wxLEFT|wxEXPAND, 10);
    grid_sizer_4->Add(ResourceFilterTextCtrl, 0, wxLEFT|wxRIGHT|wxEXPAND, 5);
    grid_sizer_4->Add(button_4, 0, wxLEFT|wxEXPAND, 10);
    grid_sizer_4->Add(ProjectFilterTextCtrl, 0, wxLEFT|wxRIGHT|wxEXPAND, 5);
    grid_sizer_4->AddGrowableCol(1);
    sizer_6->Add(grid_sizer_4, 1, wxEXPAND, 0);
    sizer_10->Add(AddIssueButton, 0, wxRIGHT|wxALIGN_CENTER_VERTICAL, 10);
    sizer_6->Add(sizer_10, 0, wxEXPAND, 0);
    sizer_3->Add(sizer_6, 0, wxEXPAND, 0);
    milestonePanel->SetSizer(sizer_3);
    grid_sizer_1->Add(label_1, 0, 0, 0);
    grid_sizer_1->Add(nameTextCtrl, 1, wxEXPAND, 0);
    grid_sizer_1->Add(button_1, 0, 0, 0);
    grid_sizer_1->Add(projectsTextCtrl, 0, wxEXPAND, 0);
    grid_sizer_1->Add(button_2, 0, 0, 0);
    grid_sizer_1->Add(resourceTextCtrl, 0, wxEXPAND, 0);
    grid_sizer_1->Add(label_3, 0, 0, 0);
    grid_sizer_1->Add(descriptionTextCtrl, 1, wxEXPAND, 0);
    grid_sizer_1->AddGrowableRow(3);
    grid_sizer_1->AddGrowableCol(1);
    sizer_8->Add(grid_sizer_1, 1, wxTOP|wxEXPAND, 10);
    sizer_7->Add(sizer_8, 1, wxEXPAND, 0);
    sizer_11->Add(milestoneCheckBox, 0, wxLEFT|wxALIGN_CENTER_VERTICAL, 10);
    sizer_11->Add(0, 0, 1, 0, 0);
    sizer_11->Add(dependencyButton, 0, wxALL|wxEXPAND, 10);
    sizer_7->Add(sizer_11, 0, wxEXPAND, 0);
    grid_sizer_2->Add(label_4, 0, 0, 0);
    grid_sizer_2->Add(label_5, 0, 0, 0);
    grid_sizer_2->Add(startCalendarCtrl, 0, wxEXPAND, 0);
    grid_sizer_2->Add(endCalendarCtrl, 0, wxEXPAND, 0);
    grid_sizer_2->AddGrowableRow(1);
    grid_sizer_2->AddGrowableCol(0);
    grid_sizer_2->AddGrowableCol(1);
    sizer_1->Add(grid_sizer_2, 1, 0, 0);
    sizer_7->Add(sizer_1, 0, wxEXPAND, 0);
    sizer_7->Add(statusBox, 0, wxEXPAND, 0);
    switchPanel->SetSizer(sizer_7);
    editSizer->Add(switchPanel, 1, wxEXPAND, 0);
    editPanel->SetSizer(editSizer);
    splitWindow->SplitVertically(milestonePanel, editPanel, 613);
    sizer_2->Add(splitWindow, 1, wxEXPAND, 0);
    topSizer->Add(sizer_2, 1, wxEXPAND, 0);
    SetSizer(topSizer);
    Layout();
    // end wxGlade
}

