// -*- C++ -*- generated by wxGlade 0.6.3 on Tue Jan  6 12:15:21 2009

#include <wx/wx.h>
#include <wx/image.h>

#ifndef LITGENERATEDFRAME_H
#define LITGENERATEDFRAME_H

// begin wxGlade: ::dependencies
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/notebook.h>
#include <wx/calctrl.h>
// end wxGlade

// begin wxGlade: ::extracode
#include "litIssueList.h"
#include "litIssueGantt.h"
#include "litTrend.h"
// end wxGlade


class litGeneratedFrame: public wxFrame {
public:
    // begin wxGlade: litGeneratedFrame::ids
    enum {
        ID_ListCtrl = wxID_HIGHEST + 1000,
        ID_IssueGantt = wxID_HIGHEST + 1001,
        ID_IssueTrend = wxID_HIGHEST + 1002,
        ID_Notebook = wxID_HIGHEST + 1003,
        ID_PlannedCheckBox = wxID_HIGHEST + 1004,
        ID_FinishedCheckBox = wxID_HIGHEST + 1005,
        ID_DelayedCheckBox = wxID_HIGHEST + 1006,
        ID_CanceledCheckBox = wxID_HIGHEST + 1007,
        ID_StartedCheckBox = wxID_HIGHEST + 1008,
        ID_AllCheckBox = wxID_HIGHEST + 1009,
        ID_ResourcesFilter = wxID_HIGHEST + 1010,
        ID_ResourceFilterTextCtrl = wxID_HIGHEST + 1011,
        ID_ProjectsFilter = wxID_HIGHEST + 1012,
        ID_ProjectFilterTextCtrl = wxID_HIGHEST + 1013,
        ID_AddIssue = wxID_HIGHEST + 1014,
        ID_NameTextCtrl = wxID_HIGHEST + 1015,
        ID_Projects = wxID_HIGHEST + 1016,
        ID_ProjectsTextCtrl = wxID_HIGHEST + 1017,
        ID_Resources = wxID_HIGHEST + 1018,
        ID_ResourceTextCtrl = wxID_HIGHEST + 1019,
        ID_DescriptionTextCtrl = wxID_HIGHEST + 1020,
        ID_MilestoneCheckBox = wxID_HIGHEST + 1021,
        ID_DependencyButton = wxID_HIGHEST + 1022,
        ID_StartCalendarCtrl = wxID_HIGHEST + 1023,
        ID_EndCalendarCtrl = wxID_HIGHEST + 1024,
        ID_StatusBox = wxID_HIGHEST + 1025
    };
    // end wxGlade

    litGeneratedFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: litGeneratedFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: litGeneratedFrame::attributes
    wxStaticBox* sizer_1_staticbox;
    wxStaticBox* sizer_8_staticbox;
    wxStaticBox* sizer_6_staticbox;
    wxMenuBar* mainFrame_menubar;
    litIssueList* milestoneListCtrl;
    wxPanel* mainNotebook_1;
    litIssueGantt* issueGantt;
    wxPanel* mainNotebook_pane_2;
    litTrend* issueTrend;
    wxPanel* mainNotebook_pane_3;
    wxNotebook* mainNotebook;
    wxCheckBox* plannedCheckBox;
    wxCheckBox* finishedCheckBox;
    wxCheckBox* delayedCheckBox;
    wxCheckBox* canceledCheckBox;
    wxCheckBox* startedCheckBox;
    wxCheckBox* allCheckBox;
    wxButton* button_3;
    wxTextCtrl* ResourceFilterTextCtrl;
    wxButton* button_4;
    wxTextCtrl* ProjectFilterTextCtrl;
    wxButton* AddIssueButton;
    wxPanel* milestonePanel;
    wxStaticText* label_1;
    wxTextCtrl* nameTextCtrl;
    wxButton* button_1;
    wxTextCtrl* projectsTextCtrl;
    wxButton* button_2;
    wxTextCtrl* resourceTextCtrl;
    wxStaticText* label_3;
    wxTextCtrl* descriptionTextCtrl;
    wxCheckBox* milestoneCheckBox;
    wxButton* dependencyButton;
    wxStaticText* label_4;
    wxStaticText* label_5;
    wxCalendarCtrl* startCalendarCtrl;
    wxCalendarCtrl* endCalendarCtrl;
    wxRadioBox* statusBox;
    wxPanel* switchPanel;
    wxPanel* editPanel;
    wxSplitterWindow* splitWindow;
    // end wxGlade
}; // wxGlade: end class


#endif // LITGENERATEDFRAME_H
